p8/urls.py
from django.contrib import admin
from django.urls import path,include
import rsk2
from rsk2 import views

urlpatterns = [
    path('admin/', admin.site.urls),
    path('sample/',views.sample,name="sample"),
    path('rsk2/',include("rsk2.urls")),
]

rsk2/urls.py
from django.urls import path
from rsk2  import views
app_name="rsk2"

urlpatterns = [
    path('',views.index,name="index"),
    path('home',views.home,name="home"),
    path('fact/<n>',views.fact,name="fact"),
    path('child',views.child,name="child"),
    path('base',views.base,name="base"),
   
]

rsk2/models.py
from django.db import models

# Create your models here.

rsk2/views.py
from django.shortcuts import render
from django.http import HttpResponse
from math import factorial
# Create your views here.

def index(request):
    return HttpResponse("<h1>welcome to views of an app</h1>")

def home(request):
    return render(request,"rsk2/home.html",{'name':"karthi"})

def fact(request,n):
    n=int(n)
    return HttpResponse("<h3>factorial is {}</h3>".format(factorial(n)))

def child(request):
    return render(request,"child.html")

def base(request):
    return render(request,"rsk2/base.html")

def sample(request):
    return render(request,"rsk2/sample.html")

templates/child.html
{% extends "rsk2/base.html" %}

{% block title %}
  <title>child html</title>
{% endblock %}

{% block content %}
  <h1>welcome to child.html</h1>
  <a href="{% url 'rsk2:home' %}">home</a>
  <a href="{% url 'sample' %}">sample</a>
{% endblock %}

templates/rsk2/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% block title %}
    <title>base html</title>
    {% endblock %}
</head>
<body>
    <h2>Navbar</h2>
    {% block content %}
    <h1>welcome to base.html</h1>
    {% endblock %}

</body>
</html>

templates/rsk2/home.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>demo of app</title>
</head>
<body>
    <h2>WELCOME TO HTML PAGE</h2>
    <h3>{{name}}</h3>
    <a href="{% url 'rsk2:child' %}">child</a>
    <a href="{% url 'sample' %}">sample</a>
</body>
</html>

templates/rsk2/sample.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>welcome to sample</title>
</head>
<body>
    <h1>welcome to sample.html</h1>
    <a href="{% url 'rsk2:child' %}">Child</a>
    <a href="{% url 'rsk2:home' %}">Home</a>
</body>
</html>